name: food_delivery
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.0.9
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.4.0
  retrofit: ^3.0.1+1
  shared_preferences: ^2.0.13
  counter: ^0.2.2

dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.5
  lint: ^1.8.2
  retrofit_generator: ^4.0.1
  
flutter:
  generate: true
  uses-material-design: true
  fonts:
   - family: Ramillas
     fonts:
     - asset: assets/Fontspring-DEMO-tt_ramillas_extrabold.otf